meta:
  created: 2023-06-06T18:41:18+02:00
  edited: 2023-06-06T18:41:18+02:00
data:
  title: Securing Cloud Native Applications at Scale
  date:
  speakers:
    - name: Mathias Conradt
      affiliation: Snyk
  event: hashicorp-user-group-12-2023-06-06
